### ISSUE TITLE
Isn't rendering graphs ;(

### ISSUE THREAD

**Issue by JohnMcLear** [marcelklehr/ep_ether-o-meter#5]

**Comment by marcelklehr** [comment]
:(

**Comment by marcelklehr** [comment]
I don't have time to look into this, sadly, but I'd happily transfer the repo :)

Also :wave: :blush:

**Comment by JohnMcLear** [comment]
:D  will try to fix.  <3

**Comment by JohnMcLear** [comment]
gimme wirte access to repo plz unless you want me to send PR
also gimme npmjs publish privs

**Comment by marcelklehr** [comment]
You can haz write access!

**Comment by JohnMcLear** [comment]
Oh I was visiting /stats not /metrics :D

**Comment by marcelklehr** [comment]
Wutts your npm handle?

**Comment by marcelklehr** [comment]
So, it does work?

**Comment by JohnMcLear** [comment]
``johnyma22``
yea it works, It just didn't say in readme how to use it ;)  I saw ``stats`` and browsed to that

**Comment by marcelklehr** [comment]
heh, added you anyways :)

Can't believe this was 6 years ago :scream_cat:
